import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./(components)/Navbar";

// Configura fuentes y variables CSS
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata del sitio (solo en Server Components)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout (Server Component)
 * - Envuelve con Providers (cliente) para React Query y otros contextos.
 * - Renderiza barra de navegación y children.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white text-black h-full`}
      >
        <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
